
CREATE DATABASE resaTestDb;
USE resaTestDb;

CREATE TABLE Vendor (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL
);

CREATE TABLE Buyer (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    CompanyName VARCHAR(255) NOT NULL
);

CREATE TABLE Appointment (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Type VARCHAR(255) NOT NULL,
    Location VARCHAR(255) NOT NULL,
    Host INT,
    Client INT,
    StartTime DATETIME NOT NULL,
    EndTime DATETIME NOT NULL,
    FOREIGN KEY (Host) REFERENCES Vendor(Id),
    FOREIGN KEY (Client) REFERENCES Buyer(Id)
);